### ISSUE TITLE
Añadir Perfil lado izquierdo en las tajetas

### ISSUE THREAD

**Issue by ValleGalan** [cdyurquina/devtech-podcast-web#3]
Buenas dias Cristian , me gustaria agregarme como un integrante de tu equipo . Voy a estar añadiendo mi perfil en el lado "Izquierdo" como acordamos previamente. Saludos :D

**Comment by ValleGalan** [comment]
Asi quedaria al añadir los cambios :
![image](https://user-images.githubusercontent.com/77822150/179238692-d58716d3-005e-4434-ba35-4b0be06465ad.png)

**Comment by cdyurquina** [comment]
Perfecto María, revisaré los cambios para continuar.

Saludos!
